### ISSUE TITLE
Mod backport?

### ISSUE THREAD

**Issue by Scarlaid** [MicrocontrollersDev/ShakeTweaks#1]
Yeah I'm still on 1.19.4 because a lot have not been updated to 1.20.1 🗿

I have tried your ShakeTweaks and CrosshairTweaks on 1.20.1 and this is what I need since Patcher from 1.8.9
It is possible, like the title said?

**Comment by MicrocontrollersDev** [comment]
Should be possible, I think the code is the exact same for 1.19 as 1.20, will see about that later today when I get the time. Will probably do backports for ShakeTweaks, CrosshairTweaks, and OverlayTweaks

**Comment by MicrocontrollersDev** [comment]
ShakeTweaks 1.19.4 https://modrinth.com/mod/shaketweaks/version/LzU12psV

**Comment by MicrocontrollersDev** [comment]
CrosshairTweaks 1.19.4 https://modrinth.com/mod/crosshairtweaks/version/hVvgSOm5

**Comment by MicrocontrollersDev** [comment]
OverlayTweaks 1.19.4 was also created but since that mod is still under review on modrinth cant link a release, please open a new issue if the backports are broken for these mods, thanks!

**Comment by Scarlaid** [comment]
thanks man 😁
