### ISSUE TITLE
Configuration does not save

### ISSUE THREAD

**Issue by Scarlaid** [MicrocontrollersDev/ShakeTweaks#2]
I find out all both of the mods have blank config file (it only displays `{}` and that's it)
This leads to the mods don't save the settings for next launch

**Comment by Scarlaid** [comment]
oh wait never mind somehow my config folder was on read-only

**Comment by Scarlaid** [comment]
nope wasn't it, Prism Launcher put all its folder in read-only state

**Comment by MicrocontrollersDev** [comment]
Can confirm, will look into this later

**Comment by MicrocontrollersDev** [comment]
This should be fixed as of 1.0.1. Please test and let me know, thanks

**Comment by Scarlaid** [comment]
can confirm, it saves the config now, though **ShakeTweaks** somehow has `Disable Screen Bobbing` enabled by default

**Comment by MicrocontrollersDev** [comment]
Yeah i added some defaults. I put what I thought most people would be downloading the mod for or are small tweaks most people probably wont even notice so might as well (like in crosshair tweaks disable in containers)
